{
  "hash": "c6e2e805b12e3094c260c04fb4795d79",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Sesión 10: Pruebas Diagnósticas II\"\nsubtitle: \"Curvas ROC, Área Bajo la Curva (AUC) y Punto de Corte Óptimo\"\nauthor: \"Jesús Esteban Hernández\"\ndate: last-modified\nformat:\n  html:\n    toc: true\n    code-fold: show\n---\n\n# Curvas ROC y Punto de Corte Óptimo\n\nEn esta sesión evaluamos marcadores diagnósticos continuos mediante el análisis de curvas ROC (*Receiver Operating Characteristic*) y la estimación del área bajo la curva (AUC).\n\n## 1. Carga de librerías y datos\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(pROC)\nlibrary(ggplot2)\n\n# Dataset aSAH: Evaluación del biomarcador s100b para mal pronóstico (outcome)\ndata(aSAH)\nhead(aSAH)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   gos6 outcome gender age wfns s100b  ndka\n29    5    Good Female  42    1  0.13  3.01\n30    5    Good Female  37    1  0.14  8.54\n31    5    Good Female  42    1  0.10  8.09\n32    5    Good Female  27    1  0.04 10.42\n33    1    Poor Female  42    3  0.13 17.40\n34    1    Poor   Male  48    2  0.10 12.75\n```\n\n\n:::\n:::\n\n\n## 2. Construcción de la curva ROC y cálculo del AUC\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Objeto ROC (outcome: 'Good' vs 'Poor')\nroc_s100b <- roc(\n  response = aSAH$outcome,\n  predictor = aSAH$s100b,\n  levels = c(\"Good\", \"Poor\"), # Control / Caso\n  direction = \"<\"             # \"<\" indica que valores más altos sugieren el caso (\"Poor\")\n)\n\n# Área bajo la curva (AUC)\nauc(roc_s100b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nArea under the curve: 0.7314\n```\n\n\n:::\n\n```{.r .cell-code}\n# Intervalo de confianza al 95% para el AUC (Delong)\nci.auc(roc_s100b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI: 0.6301-0.8326 (DeLong)\n```\n\n\n:::\n:::\n\n\n## 3. Representación gráfica de la curva ROC\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(\n  roc_s100b,\n  main = \"Evaluación Diagnóstica: S100b\",\n  col = \"#2E9FDF\",\n  lwd = 3,\n  print.auc = TRUE,\n  print.auc.x = 0.4,\n  print.auc.y = 0.2,\n  auc.polygon = TRUE,\n  auc.polygon.col = \"#2E9FDF22\",\n  grid = TRUE\n)\n\n# Añadir IC del 95% dibujado sobre la curva\nci_sp <- ci.se(roc_s100b, specificities = seq(0, 1, 0.1))\nplot(ci_sp, type = \"shape\", col = \"#2E9FDF11\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in plot.ci.se(ci_sp, type = \"shape\", col = \"#2E9FDF11\"): Low definition\nshape.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Curva ROC para el biomarcador S100b con intervalo de confianza](sesion10_files/figure-html/fig-roc-plot-1.png){#fig-roc-plot width=672}\n:::\n:::\n\n\n## 4. Determinación del Punto de Corte Óptimo (Índice de Youden)\n\nEl índice de Youden maximiza la distancia vertical respecto a la diagonal de azar ($J = \\text{Sensibilidad} + \\text{Especificidad} - 1$):\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extracción del punto de corte óptimo por el método de Youden\ncorte_optimo <- coords(\n  roc_s100b, \n  x = \"best\", \n  best.method = \"youden\",\n  ret = c(\"threshold\", \"sensitivity\", \"specificity\", \"ppv\", \"npv\")\n)\n\ncorte_optimo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          threshold sensitivity specificity  ppv       npv\nthreshold     0.205   0.6341463   0.8055556 0.65 0.7945205\n```\n\n\n:::\n:::\n\n\n---\n\n### Interpretación Clínica\n\n* **Punto de corte óptimo:** 0.205\n* **Sensibilidad:** 63.4%\n* **Especificidad:** 80.6%\n\n",
    "supporting": [
      "sesion10_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}